//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

pub use super::bgm_data::Entity as BgmData;
pub use super::collections::Entity as Collections;
pub use super::game_collection_link::Entity as GameCollectionLink;
pub use super::game_sessions::Entity as GameSessions;
pub use super::game_statistics::Entity as GameStatistics;
pub use super::games::Entity as Games;
pub use super::other_data::Entity as OtherData;
pub use super::savedata::Entity as Savedata;
pub use super::user::Entity as User;
pub use super::vndb_data::Entity as VndbData;
