//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::FromJsonQueryResult;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// BGM 授权信息。
///
/// 旧手动 token 只有 access_token；OAuth 登录会包含 refresh_token 和 expires_at。
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
#[serde(default)]
pub struct BgmAuth {
    pub access_token: String,
    pub refresh_token: Option<String>,
    pub expires_at: Option<i64>,
    pub username: Option<String>,
    pub nickname: Option<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
#[serde(default, rename_all = "camelCase")]
pub struct ThemePalette {
    pub primary: Option<String>,
    pub secondary: Option<String>,
    pub background_default: Option<String>,
    pub background_paper: Option<String>,
    pub text_primary: Option<String>,
    pub text_secondary: Option<String>,
    pub divider: Option<String>,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub bgm_auth: Option<BgmAuth>,
    #[sea_orm(column_type = "Text", nullable)]
    pub vndb_token: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub save_root_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub db_backup_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub install_root_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub le_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub magpie_path: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub theme_mode: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub active_theme_package_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub custom_theme_light_palette: Option<ThemePalette>,
    #[sea_orm(column_type = "Text", nullable)]
    pub custom_theme_dark_palette: Option<ThemePalette>,
    #[sea_orm(column_type = "Text")]
    pub theme_apply_scope: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub theme_background_path: Option<String>,
    pub theme_background_width: Option<i32>,
    pub theme_background_height: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub theme_background_hash: Option<String>,
    pub theme_background_updated_at: Option<i64>,
    pub theme_overlay_opacity: f64,
    pub theme_blur: f64,
    #[sea_orm(column_type = "Text")]
    pub theme_background_size: String,
    #[sea_orm(column_type = "Text")]
    pub theme_accent_color: String,
}

impl Model {
    pub fn save_root_path_value(&self) -> Option<&str> {
        self.save_root_path.as_deref()
    }

    pub fn db_backup_path_value(&self) -> Option<&str> {
        self.db_backup_path.as_deref()
    }

    pub fn install_root_path_value(&self) -> Option<&str> {
        self.install_root_path.as_deref()
    }

    #[cfg(target_os = "windows")]
    pub fn le_path_value(&self) -> Option<&str> {
        self.le_path.as_deref()
    }

    #[cfg(target_os = "windows")]
    pub fn magpie_path_value(&self) -> Option<&str> {
        self.magpie_path.as_deref()
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
