//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

pub mod prelude;

pub mod bgm_data;
pub mod collections;
pub mod game_collection_link;
pub mod game_sessions;
pub mod game_statistics;
pub mod games;
pub mod other_data;
pub mod savedata;
pub mod user;
pub mod vndb_data;
